replicaCount: 2
image:
  repository: "registry.cn-shanghai.aliyuncs.com/huyi/springboot-k8s"
  pullPolicy: Always
app:
  appName: "springboot-k8s"

fullnameOverride:
  enabled: true
ingress:
  enabled: true
  hosts[0]:
    host: "helm.ibestfanli.com"
    paths[0]: "/springboot-k8s"

nameOverride: "springboot-k8s"

imagePullSecrets[0]:
  name: "registrysecret"

